---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    clickhouse_host: "127.0.0.1"

  tasks:
    - name: Include vector role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
