---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create docker containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: "{{ item.command | default('sleep infinity') }}"
        privileged: "{{ item.privileged | default(true) }}"
      loop: "{{ molecule_yml.platforms }}"

    - name: Add containers to inventory
      ansible.builtin.add_host:
        name: "{{ item.name }}"
        groups: molecule
        ansible_connection: docker
      loop: "{{ molecule_yml.platforms }}"
