---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Check vector binary exists
      ansible.builtin.stat:
        path: /opt/vector/bin/vector
      register: vector_binary

    - name: Assert vector binary exists
      ansible.builtin.assert:
        that:
          - vector_binary.stat.exists
        fail_msg: "Vector binary not found"
        success_msg: "Vector binary exists"

    - name: Check vector config exists
      ansible.builtin.stat:
        path: /etc/vector/vector.yml
      register: vector_config

    - name: Assert vector config exists
      ansible.builtin.assert:
        that:
          - vector_config.stat.exists
        fail_msg: "Vector config not found"
        success_msg: "Vector config exists"

    - name: Validate vector config syntax
      ansible.builtin.command: /opt/vector/bin/vector validate --no-environment /etc/vector/vector.yml
      register: vector_validate
      changed_when: false

    - name: Assert vector config is valid
      ansible.builtin.assert:
        that:
          - vector_validate.rc == 0
        fail_msg: "Vector config is invalid"
        success_msg: "Vector config is valid"
